export const Events = Object.freeze({
  LANDING: "landing",
  LOCK_SOLVED: "lock_solved",
  LOCK_ALREADY_SOLVED: "lock_already_solved",
  LOCK_NO_SOLUTION: "lock_no_solution",
  LOCK_BECAME_MAPPABLE: "lock_became_mappable",
  SOLVE_BUTTON_CLICKED: "solve_button_clicked",
  EXAMPLE_LOCK_LOADED: "example_lock_loaded",
  GUIDE_OPENED: "guide_opened",
  WALKTHROUGH_STEP_CHANGED: "walkthrough_step_changed",
  WALKTHROUGH_UI_TOGGLED: "walkthrough_ui_toggled",
  PROMPT_DISMISSED: "prompt_dismissed",
  SHARE_LINK_COPIED: "share_link_copied",
  SHARE_LINK_COPY_FAILED: "share_link_copy_failed",
  SHARE_PROMPT_SHOWN: "share_prompt_shown",
  SHARE_PROMPT_CLICKED: "share_prompt_clicked",
  LOCK_CLEARED: "lock_cleared",
  ONBOARDING_STEP_VIEWED: "onboarding_step_viewed",
  ONBOARDING_DISMISSED: "onboarding_dismissed",
  TUTOR_STARTED: "tutor_started",
  TUTOR_NOT_SHOWN: "tutor_not_shown",
  TUTOR_NEXT_CLICKED: "tutor_next_clicked",
  TUTOR_SKIPPED: "tutor_skipped",
  MASTERY_TIER_CHANGED: "mastery_tier_changed",
  STEP_MISMATCH_CLICKED: "step_mismatch_clicked",
});
